#define ROW1  "    #                 #                                #            "
#define ROW2  "    #                 #              #########         #            "
#define ROW3  "    #                 #      #             ##          #            "
#define ROW4  "    #   #####         #      ##           ##           #   #####    "
#define ROW5  " ####  ##   ##    ########    ##         ##         ####  ##   ##   "
#define ROW6  "    # ##     ##       #   #    #        ##             # ##     ##  "
#define ROW7  "    ###       #       #   #    ##      #######         ###       #  "
#define ROW8  "    ##        #      ##   #     #     ##     ##        ##        #  "
#define ROW9  "    #         #      #    #     #    ##       ##       #         #  "
#define ROW10 "   ##         #      #    #         ##         #      ##         #  "
#define ROW11 "  ###         #     ##    #            ###     #     ###         #  "
#define ROW12 " ## #        ##     #     #           #  ##    #    ## #        ##  "
#define ROW13 "    #       ##     ##    ##           #   #   ##       #       ##   "
#define ROW14 "    #     ###     ##     #            ##  #  ##        #     ###    "
#define ROW15 "    #                  ###             #######         #            "
