services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    tty: true
    image: wkrw
    container_name: wkrw-container
    environment:
      TZ: 'Asia/Tokyo'
    network_mode: 'host'
